version: '3.7'
services:
    blog_db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=trq371402
        volumes:
            - type: bind
              source: /home/runqi/Workspace/Blog/db/
              target: /docker-entrypoint-initdb.d/
    blog_server:
        image: testimg
        ports:
            - "5000:5000"
        depends_on:
            - "blog_db"
